# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/139/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/139/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nassim/Desktop/projects/ProjetRF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nassim/Desktop/projects/ProjetRF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/139/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/139/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nassim/Desktop/projects/ProjetRF/CMakeFiles /home/nassim/Desktop/projects/ProjetRF/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nassim/Desktop/projects/ProjetRF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProjetRF

# Build rule for target.
ProjetRF: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProjetRF
.PHONY : ProjetRF

# fast build rule for target.
ProjetRF/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/build
.PHONY : ProjetRF/fast

Data/Core.o: Data/Core.cpp.o

.PHONY : Data/Core.o

# target to build an object file
Data/Core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Core.cpp.o
.PHONY : Data/Core.cpp.o

Data/Core.i: Data/Core.cpp.i

.PHONY : Data/Core.i

# target to preprocess a source file
Data/Core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Core.cpp.i
.PHONY : Data/Core.cpp.i

Data/Core.s: Data/Core.cpp.s

.PHONY : Data/Core.s

# target to generate assembly for a file
Data/Core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Core.cpp.s
.PHONY : Data/Core.cpp.s

Data/Data.o: Data/Data.cpp.o

.PHONY : Data/Data.o

# target to build an object file
Data/Data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Data.cpp.o
.PHONY : Data/Data.cpp.o

Data/Data.i: Data/Data.cpp.i

.PHONY : Data/Data.i

# target to preprocess a source file
Data/Data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Data.cpp.i
.PHONY : Data/Data.cpp.i

Data/Data.s: Data/Data.cpp.s

.PHONY : Data/Data.s

# target to generate assembly for a file
Data/Data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Data.cpp.s
.PHONY : Data/Data.cpp.s

Data/Kmeans.o: Data/Kmeans.cpp.o

.PHONY : Data/Kmeans.o

# target to build an object file
Data/Kmeans.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Kmeans.cpp.o
.PHONY : Data/Kmeans.cpp.o

Data/Kmeans.i: Data/Kmeans.cpp.i

.PHONY : Data/Kmeans.i

# target to preprocess a source file
Data/Kmeans.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Kmeans.cpp.i
.PHONY : Data/Kmeans.cpp.i

Data/Kmeans.s: Data/Kmeans.cpp.s

.PHONY : Data/Kmeans.s

# target to generate assembly for a file
Data/Kmeans.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Kmeans.cpp.s
.PHONY : Data/Kmeans.cpp.s

Data/KmeansEM.o: Data/KmeansEM.cpp.o

.PHONY : Data/KmeansEM.o

# target to build an object file
Data/KmeansEM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/KmeansEM.cpp.o
.PHONY : Data/KmeansEM.cpp.o

Data/KmeansEM.i: Data/KmeansEM.cpp.i

.PHONY : Data/KmeansEM.i

# target to preprocess a source file
Data/KmeansEM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/KmeansEM.cpp.i
.PHONY : Data/KmeansEM.cpp.i

Data/KmeansEM.s: Data/KmeansEM.cpp.s

.PHONY : Data/KmeansEM.s

# target to generate assembly for a file
Data/KmeansEM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/KmeansEM.cpp.s
.PHONY : Data/KmeansEM.cpp.s

Data/Knn.o: Data/Knn.cpp.o

.PHONY : Data/Knn.o

# target to build an object file
Data/Knn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Knn.cpp.o
.PHONY : Data/Knn.cpp.o

Data/Knn.i: Data/Knn.cpp.i

.PHONY : Data/Knn.i

# target to preprocess a source file
Data/Knn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Knn.cpp.i
.PHONY : Data/Knn.cpp.i

Data/Knn.s: Data/Knn.cpp.s

.PHONY : Data/Knn.s

# target to generate assembly for a file
Data/Knn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Knn.cpp.s
.PHONY : Data/Knn.cpp.s

Data/Tester.o: Data/Tester.cpp.o

.PHONY : Data/Tester.o

# target to build an object file
Data/Tester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Tester.cpp.o
.PHONY : Data/Tester.cpp.o

Data/Tester.i: Data/Tester.cpp.i

.PHONY : Data/Tester.i

# target to preprocess a source file
Data/Tester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Tester.cpp.i
.PHONY : Data/Tester.cpp.i

Data/Tester.s: Data/Tester.cpp.s

.PHONY : Data/Tester.s

# target to generate assembly for a file
Data/Tester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/Data/Tester.cpp.s
.PHONY : Data/Tester.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProjetRF.dir/build.make CMakeFiles/ProjetRF.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ProjetRF"
	@echo "... Data/Core.o"
	@echo "... Data/Core.i"
	@echo "... Data/Core.s"
	@echo "... Data/Data.o"
	@echo "... Data/Data.i"
	@echo "... Data/Data.s"
	@echo "... Data/Kmeans.o"
	@echo "... Data/Kmeans.i"
	@echo "... Data/Kmeans.s"
	@echo "... Data/KmeansEM.o"
	@echo "... Data/KmeansEM.i"
	@echo "... Data/KmeansEM.s"
	@echo "... Data/Knn.o"
	@echo "... Data/Knn.i"
	@echo "... Data/Knn.s"
	@echo "... Data/Tester.o"
	@echo "... Data/Tester.i"
	@echo "... Data/Tester.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

